
%walking data
pwpk=table_creation("data/walking-priya.xls","walking");
awpk = table_creation('data/walking_data_(flat)_auri.xls',"walking");
swpk=table_creation('data/walking(flat)_sharon.xls', "walking");


%Running Data

prpk=table_creation('data/running-priya.xls',"running");
arpk=table_creation('data/auri_run.xls',"running");
srpk= table_creation('data/running(flat)_sharon.xls',"running");

%Jumping data

pjpk= table_creation('data/jumping-priya.xls',"jumping");
ajpk=table_creation('data/auri_jump.xls',"jumping");
sjpk=table_creation('data/jumping(flat)_sharon.xls',"jumping");

%%
%Combine peaks data
Featurespeak=[pwpk;prpk,;pjpk,;awpk;arpk;ajpk;swpk;srpk;sjpk]

%%
[trainedClassifier, validationAccuracy]=trainClassifier(Featurespeak)

%%
function [x_p y_p] = minamp20peaks(v,x, y)
   
    x_p = [] ;
    y_p = [] ;
    a = 1 ; 
    
    for i = 1:length(x)
        if  i == 1 || i == length(x)
            a;
            continue
            
        elseif (y(i+1) < y(i)) && (y(i-1) < y(i)) && y(i)>v
            
                x_p(a) = x(i) ;
                y_p(a) = y(i) ;
                a = a + 1 ;
                
        elseif a>20
               a;
               break
        else 
            continue
                
        end
    
    end
end    

function [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 02-May-2021 20:22:49


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'A_xpeak', 'A_ypeak', 'A_zpeak', 'A_abspeak'};
predictors = inputTable(:, predictorNames);
response = inputTable.Motion;
isCategoricalPredictor = [false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.

% Expand the Distribution Names per predictor
% Numerical predictors are assigned either Gaussian or Kernel distribution and categorical predictors are assigned mvmn distribution
% Gaussian is replaced with Normal when passing to the fitcnb function
distributionNames =  repmat({'Normal'}, 1, length(isCategoricalPredictor));
distributionNames(isCategoricalPredictor) = {'mvmn'};

if any(strcmp(distributionNames,'Kernel'))
    classificationNaiveBayes = fitcnb(...
        predictors, ...
        response, ...
        'Kernel', 'Normal', ...
        'Support', 'Unbounded', ...
        'DistributionNames', distributionNames, ...
        'ClassNames', {'jumping'; 'running'; 'walking'});
else
    classificationNaiveBayes = fitcnb(...
        predictors, ...
        response, ...
        'DistributionNames', distributionNames, ...
        'ClassNames', {'jumping'; 'running'; 'walking'});
end

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
naiveBayesPredictFcn = @(x) predict(classificationNaiveBayes, x);
trainedClassifier.predictFcn = @(x) naiveBayesPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'A_abspeak', 'A_xpeak', 'A_ypeak', 'A_zpeak'};
trainedClassifier.ClassificationNaiveBayes = classificationNaiveBayes;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2020b.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'A_xpeak', 'A_ypeak', 'A_zpeak', 'A_abspeak'};
predictors = inputTable(:, predictorNames);
response = inputTable.Motion;
isCategoricalPredictor = [false, false, false, false];

% Set up holdout validation
cvp = cvpartition(response, 'Holdout', 0.2);
trainingPredictors = predictors(cvp.training, :);
trainingResponse = response(cvp.training, :);
trainingIsCategoricalPredictor = isCategoricalPredictor;

% Train a classifier
% This code specifies all the classifier options and trains the classifier.

% Expand the Distribution Names per predictor
% Numerical predictors are assigned either Gaussian or Kernel distribution and categorical predictors are assigned mvmn distribution
% Gaussian is replaced with Normal when passing to the fitcnb function
distributionNames =  repmat({'Normal'}, 1, length(trainingIsCategoricalPredictor));
distributionNames(trainingIsCategoricalPredictor) = {'mvmn'};

if any(strcmp(distributionNames,'Kernel'))
    classificationNaiveBayes = fitcnb(...
        trainingPredictors, ...
        trainingResponse, ...
        'Kernel', 'Normal', ...
        'Support', 'Unbounded', ...
        'DistributionNames', distributionNames, ...
        'ClassNames', {'jumping'; 'running'; 'walking'});
else
    classificationNaiveBayes = fitcnb(...
        trainingPredictors, ...
        trainingResponse, ...
        'DistributionNames', distributionNames, ...
        'ClassNames', {'jumping'; 'running'; 'walking'});
end

% Create the result struct with predict function
naiveBayesPredictFcn = @(x) predict(classificationNaiveBayes, x);
validationPredictFcn = @(x) naiveBayesPredictFcn(x);

% Add additional fields to the result struct


% Compute validation predictions
validationPredictors = predictors(cvp.test, :);
validationResponse = response(cvp.test, :);
[validationPredictions, validationScores] = validationPredictFcn(validationPredictors);

% Compute validation accuracy
correctPredictions = strcmp( strtrim(validationPredictions), strtrim(validationResponse));
isMissing = cellfun(@(x) all(isspace(x)), validationResponse, 'UniformOutput', true);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);


% Compute validation accuracy
correctPredictions = strcmp( strtrim(validationPredictions), strtrim(validationResponse));
isMissing = cellfun(@(x) all(isspace(x)), validationResponse, 'UniformOutput', true);
correctPredictions = correctPredictions(~isMissing);
validationAccuracy = sum(correctPredictions)/length(correctPredictions);
end

function [awpk] = table_creation(file,mode)
%takes in excel file and creates table with mode column
aw_data=readmatrix(file);
awa_x = smooth_filter(aw_data(:,2));
awa_y = smooth_filter(aw_data(:,3));
awa_z = smooth_filter(aw_data(:,4));
awa_abs = smooth_filter(aw_data(:,5));
awtime = aw_data(:,1);


%acceleration of x
[awpktx,awpkx]=minamp20peaks(1.87,awtime,awa_x);
awpkx1=awpkx(:);

%acceleration of y

[awpkty,awpky]=minamp20peaks(1.87,awtime,awa_y);
awpky1=awpky(:);

%acceleration of z
[awpktz,awpkz]=minamp20peaks(1.87,awtime,awa_z);
awpkz1=awpkz(:);

%absolute acceleration
[awpkta,awpka]=minamp20peaks(1.87,awtime,awa_abs);
awpka1=awpka(:);

classaw = repmat(mode,[1 length(awpka1)]);
classaw = classaw(:);
awpk=table(awpkx1,awpky1,awpkz1,awpka1,classaw);
awpk.Properties.VariableNames = ["A_xpeak","A_ypeak","A_zpeak","A_abspeak","Motion"]


end